### ISSUE TITLE
solib?

### ISSUE THREAD

**Issue by zvezdochiot** [coherentgraphics/cpdflib-binary#1]
Maybe use `libcpdf.so.2.3` and generate `cpdf.h`?

In https://github.com/coherentgraphics/cpdf-binaries and https://github.com/coherentgraphics/cpdfsqueeze-binaries: `cpdf+libcpdf.so` and `cpdfsqueeze+libcpdf.so` of section `LinuxXXbit-shared`? Or link to https://github.com/coherentgraphics/cpdflib-binary ?

PS:
```sh
ar x libcpdf.a
gcc -Wall -shared -Wl,-soname,libcpdf.so.2 -o libcpdf.so.2.3 *.o -s
ln -s libcpdf.so.2.3 libcpdf.so.2
ln -s libcpdf.so.2 libcpdf.so
```

**Comment by johnwhitington** [comment]
Can you explain why? I don't know much about how libraries work, so I wonder if you could help me.

**Comment by zvezdochiot** [comment]
Hi @johnwhitington .

:question: What exactly needs clarification: the structure of libraries, their difference, the difference in their application or methods of their creation? These are interconnected things, but in total there will be too much.

**Comment by johnwhitington** [comment]
As far as I understand it, your original message has two suggestions:

1) A suggestion to ship shared libraries for cpdf-binaries and cpdfsqueeze-binaries as well as static libraries.

2) A suggestion which seems to be to do with the versioning of libraries and the names that linux expects them to have.

Is that correct?

**Comment by zvezdochiot** [comment]
@johnwhitington say:
>your original message has two suggestions

Yes. Exactly. And expected `cpdf.h` with the API. And the `cpdf` and` cpdfsqueeze` are linked to `libcpdf.so.2`.
